os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
  # Using -l here to change to the previous window via ":wincmd p".
  edit: "nvr -l --remote {{filename}}"
